apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres-service
    app: demo-votting-app
spec:
  selector:
    name: postgres-app-pod
    app: demo-votting-app
  ports:
  - port: 5432
    targetPort: 5432