apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: demo-votting-app
spec:
  type: LoadBalancer
  selector:
    name: result-app-pod
    app: demo-votting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
